# .github/workflows/cd.yml

name: Continuous Delivery

on:
  push:
    branches: ["master", "release/*"]

jobs:
  staging:
    name: Deploy Staging to Railway
    if: github.ref != 'refs/heads/master' && startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://be-staging.zekhoi.dev
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  production:
    name: Deploy Production to Railway
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://be-production.zekhoi.dev
    # needs: [staging]
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
