# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_DIALECT: ${{ secrets.DB_DIALECT }}
  WA_SERVICE_URL: ${{ secrets.WA_SERVICE_URL }}
  WA_SERVICE_TOKEN: ${{ secrets.WA_SERVICE_TOKEN }}
  MAILER_SENDER_EMAIL: ${{ secrets.MAILER_SENDER_EMAIL }}
  MAILER_SENDER_PASSWORD: ${{ secrets.MAILER_SENDER_PASSWORD }}

jobs:
  linttest:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run linter to check code style and formatting
        run: npm run lint

      - name: Run tests to check code functionality
        run: npm test
